import { MetalPreset } from "./types";

export const PRESETS: Record<string, MetalPreset> = {
  bronze: {
    name: "Бронза",
    metals: [
      {
        id: "copper",
        name: "Медь (Малахит)",
        color: "from-orange-500 to-amber-600",
        minPercent: 70,
        maxPercent: 80,
        defaultPercent: 75,
        dustNorm: 129,
        dustSmall: 31,
        dustTiny: 13,
      },
      {
        id: "tin",
        name: "Олово (Касситерит)",
        color: "from-slate-400 to-zinc-500",
        minPercent: 20,
        maxPercent: 30,
        defaultPercent: 25,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
    ],
  },
  brass_gt: {
    name: "Латунь (GT: Медь 88-92% / Цинк 8-12%)",
    metals: [
      {
        id: "copper",
        name: "Медь (Малахит)",
        color: "from-orange-500 to-amber-600",
        minPercent: 88,
        maxPercent: 92,
        defaultPercent: 90,
        dustNorm: 129,
        dustSmall: 31,
        dustTiny: 13,
      },
      {
        id: "zinc",
        name: "Цинк",
        color: "from-emerald-500 to-teal-600",
        minPercent: 8,
        maxPercent: 12,
        defaultPercent: 10,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
    ],
  },
  brass_tfc: {
    name: "Латунь (TFC: Медь 70-80% / Цинк 20-30%)",
    metals: [
      {
        id: "copper",
        name: "Медь (Малахит)",
        color: "from-orange-500 to-amber-600",
        minPercent: 70,
        maxPercent: 80,
        defaultPercent: 75,
        dustNorm: 129,
        dustSmall: 31,
        dustTiny: 13,
      },
      {
        id: "zinc",
        name: "Цинк",
        color: "from-emerald-500 to-teal-600",
        minPercent: 20,
        maxPercent: 30,
        defaultPercent: 25,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
    ],
  },
  red_alloy: {
    name: "Красный сплав (Redstone 75-85% / Медь 15-25%)",
    metals: [
      {
        id: "redstone",
        name: "Редстоун (Красная пыль)",
        color: "from-red-600 to-rose-700",
        minPercent: 75,
        maxPercent: 85,
        defaultPercent: 80,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
      {
        id: "copper",
        name: "Медь (Малахит)",
        color: "from-orange-500 to-amber-600",
        minPercent: 15,
        maxPercent: 25,
        defaultPercent: 20,
        dustNorm: 129,
        dustSmall: 31,
        dustTiny: 13,
      },
    ],
  },
  tin_alloy: {
    name: "Оловянный сплав (Олово 45-55% / Чугун 45-55%)",
    metals: [
      {
        id: "tin",
        name: "Олово",
        color: "from-slate-400 to-zinc-500",
        minPercent: 45,
        maxPercent: 55,
        defaultPercent: 50,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
      {
        id: "cast_iron",
        name: "Чугун (Cast Iron)",
        color: "from-gray-500 to-slate-700",
        minPercent: 45,
        maxPercent: 55,
        defaultPercent: 50,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
    ],
  },
  invar: {
    name: "Инвар (Никель 30-40% / Чугун 60-70%)",
    metals: [
      {
        id: "nickel",
        name: "Никель",
        color: "from-yellow-250 to-stone-400",
        minPercent: 30,
        maxPercent: 40,
        defaultPercent: 35,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
      {
        id: "cast_iron",
        name: "Чугун (Cast Iron)",
        color: "from-gray-500 to-slate-700",
        minPercent: 60,
        maxPercent: 70,
        defaultPercent: 65,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
    ],
  },
  potin: {
    name: "Потин (Медь 63-69% / Олово 19-25% / Свинец 8-14%)",
    metals: [
      {
        id: "copper",
        name: "Медь (Малахит)",
        color: "from-orange-500 to-amber-600",
        minPercent: 63,
        maxPercent: 69,
        defaultPercent: 66,
        dustNorm: 129,
        dustSmall: 31,
        dustTiny: 13,
      },
      {
        id: "tin",
        name: "Олово",
        color: "from-slate-400 to-zinc-500",
        minPercent: 19,
        maxPercent: 25,
        defaultPercent: 22,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
      {
        id: "lead",
        name: "Свинец",
        color: "from-indigo-600 to-slate-700",
        minPercent: 8,
        maxPercent: 14,
        defaultPercent: 12,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
    ],
  },
  cobalt_brass: {
    name: "Кобальтовая латунь (Латунь 74-81% / Кобальт 8-14% / Алюмосиликат 8-14%)",
    metals: [
      {
        id: "brass_component",
        name: "Латунь",
        color: "from-amber-400 to-yellow-600",
        minPercent: 74,
        maxPercent: 81,
        defaultPercent: 77,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
      {
        id: "cobalt",
        name: "Кобальт",
        color: "from-cyan-500 to-blue-700",
        minPercent: 8,
        maxPercent: 14,
        defaultPercent: 11,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
      {
        id: "aluminium_silicate",
        name: "Алюмосиликат",
        color: "from-teal-400 to-stone-500",
        minPercent: 8,
        maxPercent: 14,
        defaultPercent: 12,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
    ],
  },
  bismuth_bronze: {
    name: "Висмутовая бронза (Медь 50-65% / Цинк 20-30% / Висмут 10-20%)",
    metals: [
      {
        id: "copper",
        name: "Медь (Малахит)",
        color: "from-orange-500 to-amber-600",
        minPercent: 50,
        maxPercent: 65,
        defaultPercent: 55,
        dustNorm: 129,
        dustSmall: 31,
        dustTiny: 13,
      },
      {
        id: "zinc",
        name: "Цинк",
        color: "from-emerald-500 to-teal-600",
        minPercent: 20,
        maxPercent: 30,
        defaultPercent: 25,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
      {
        id: "bismuth",
        name: "Висмут",
        color: "from-pink-500 to-rose-600",
        minPercent: 10,
        maxPercent: 20,
        defaultPercent: 20,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
    ],
  },
  black_bronze: {
    name: "Черная бронза (Медь 50-70% / Серебро 10-25% / Золото 10-25%)",
    metals: [
      {
        id: "copper",
        name: "Медь",
        color: "from-orange-500 to-amber-600",
        minPercent: 50,
        maxPercent: 70,
        defaultPercent: 60,
        dustNorm: 129,
        dustSmall: 31,
        dustTiny: 13,
      },
      {
        id: "silver",
        name: "Серебро",
        color: "from-slate-300 to-gray-400",
        minPercent: 10,
        maxPercent: 25,
        defaultPercent: 20,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
      {
        id: "gold",
        name: "Золото",
        color: "from-yellow-400 to-amber-500",
        minPercent: 10,
        maxPercent: 25,
        defaultPercent: 20,
        dustNorm: 144,
        dustSmall: 36,
        dustTiny: 16,
      },
    ],
  },
  custom: {
    name: "Кастомный сплав (Ручная настройка)",
    metals: [
      {
        id: "metal_1",
        name: "Металл 1",
        color: "from-orange-500 to-amber-600",
        minPercent: 50,
        maxPercent: 80,
        defaultPercent: 75,
        dustNorm: 100,
        dustSmall: 25,
        dustTiny: 10,
      },
      {
        id: "metal_2",
        name: "Металл 2",
        color: "from-slate-400 to-zinc-500",
        minPercent: 20,
        maxPercent: 50,
        defaultPercent: 25,
        dustNorm: 100,
        dustSmall: 25,
        dustTiny: 10,
      },
    ],
  },
};
